### ISSUE TITLE
Bootstrap dropdown automation

### ISSUE THREAD

**Issue by wmolyneux** [atata-framework/atata-bootstrap#10]
Hi,

I have a bootstrap dropdown list defined similar to the one here (https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_dropdown-menu&stacked=h) and I am unable to automate selecting items in the list.

I dont seem to be able to find any examples, including in the Atata test application on how to automate such dropdowns even though the dropdown is apparently covered in this library.

Thanks

**Comment by YevgeniyShunevych** [comment]
Hi,

Check [Bootstrap Dropdown (BSDropdownToggle&lt;TOwner&gt;)](https://atata-framework.github.io/examples/bootstrap-dropdown/) example. `BSDropdownToggle<TOwner>` control is used in this example which is appeared in recently published Atata.Bootstrap v0.7.0. Don't forget to update the package.

**Comment by wmolyneux** [comment]
So it turns out the dropdown i am testing is using angular bootstrap dropdowns which are similar but slightly different. 

I have taken the source for the bootstrap dropdown you referenced and created my own component that handles the issue. The only problem I have now is the behaviour of 'ClickParent' attribute acting odd.

I would like my test to do the following, given a dropdown like the ones on the link you sent me i would like my test to do the following
```
SomePage.Actions.Item1.Should.Equal("some text");
SomePage.Actions.Item2.Should.Equal("some other text");
```

The click parent works for the first reference of a child but when it clicks the parent for Item2 is closes the dropdown. My control has the following attributes

```
[ControlFinding(FindTermBy.ChildContent)]
[ClickParent(AppliesTo = TriggerScope.Children)]
public class MyDropdown<TOwner> : Control<TOwner> where TOwner : PageObject<TOwner>
```

How can I either stop it from closing the dropdown or make it close the dropdown after each action on a child element?

**Comment by YevgeniyShunevych** [comment]
I've got your issue. Yes `[ClickParent]` always clicks drop-down before access to children. And in your case when menu is already opened then it closes drop-down and menu becomes hidden, which is wrong.

I updated [`BSDropdownToggle<TOwner>`](https://github.com/atata-framework/atata-bootstrap/blob/master/src/Atata.Bootstrap/BSDropdownToggle%601.cs) control to consider current state of drop-down menu. Thus if it is already open the click on drop-down toggle will not happen. See the code. Hope you will get an idea and successfully apply to your control. For such tricky things `[InvokeMethod]` trigger can be used.

```cs
using System.Linq;

namespace Atata.Bootstrap
{
    /// <summary>
    /// Represents Bootstrap dropdown toggle control (element with "dropdown-toggle" class).
    /// Default search is performed by the content.
    /// </summary>
    /// <typeparam name="TOwner">The type of the owner page object.</typeparam>
    [ControlDefinition(ContainingClass = BSClass.DropdownToggle, ComponentTypeName = "dropdown toggle", IgnoreNameEndings = "DropdownButton,DropDownButton,Dropdown,DropDown,Button,DropdownToggle,DropDownToggle,Toggle")]
    [ControlFinding(FindTermBy.Content)]
    [FindSettings(OuterXPath = "following-sibling::*[1]//")]
    [InvokeMethod(nameof(OnBeforeAccessChild), TriggerEvents.BeforeAccess, AppliesTo = TriggerScope.Children)]
    [InvokeMethod(nameof(OnInit), TriggerEvents.Init)]
    public class BSDropdownToggle<TOwner> : Control<TOwner>
        where TOwner : PageObject<TOwner>
    {
        [FindByClass("dropdown-menu", OuterXPath = "following-sibling::", Visibility = Visibility.Any)]
        [TraceLog]
        protected Control<TOwner> DropdownMenu { get; private set; }

        protected void OnInit()
        {
            DropdownMenu.Triggers.RemoveAll(x => x is InvokeMethodAttribute);
        }

        protected override bool GetIsEnabled()
        {
            return !Attributes.Class.Value.Contains(BSClass.Disabled);
        }

        protected void OnBeforeAccessChild()
        {
            if (!DropdownMenu.IsVisible)
                Click();
        }
    }
}
```

Note that `Visibility = Visibility.Any` is set for `DropdownMenu`.

**Comment by wmolyneux** [comment]
I'll give this a try, thanks for the speedy replies!
