### ISSUE TITLE
Override functionality for Tags

### ISSUE THREAD

**Issue by MonzT** [atata-framework/atata-bootstrap#9]
Hi

Attempting to make use of the Framework for an Angular project. 
Using the Angular BS Modal component replaces the "div" tag with "ngb-modal-window" tag automatically. Even when attempting to add a specific "div" tag around the Angular object. 

Is there a way to include functionality to override the PageObjectDefinition for the BSModal object?

**Comment by YevgeniyShunevych** [comment]
Sure. You can replace page object or control definition in inherited classes this way:

```cs
[PageObjectDefinition("ngb-modal-window", ContainingClass = "modal", ComponentTypeName = "modal", IgnoreNameEndings = "PopupWindow,Window,Popup,Modal")]
public abstract class AngularBSModal<TOwner> : BSModal<TOwner>
    where TOwner : AngularBSModal<TOwner>
{
}
```

And then inherit your popup page objects from `AngularBSModal<TOwner>`.

Or even instead of `"ngb-modal-window"` you can set `"*"` in `PageObjectDefinition` to match any element.

**Comment by MonzT** [comment]
Excellent! Thank you!!!
